// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title CredentialVerifier
 * @notice On-chain Groth16 proof verifier for ZK credential claims.
 *
 * The pairing verification logic is auto-generated by:
 *   snarkjs zkey export solidityverifier cred_final.zkey CredentialVerifierBase.sol
 *
 * This wrapper adds:
 *   - Storage of verified claim bitmaps per user
 *   - Nullifier set to prevent proof replay
 *   - Right-to-erasure support
 *   - Third-party claim checking
 */
contract CredentialVerifier {

    event CredentialVerified(address indexed user, uint256 claimBitmap);
    event CredentialCleared(address indexed user);

    mapping(address => uint256) public claimBitmaps;
    mapping(bytes32 => bool) public usedNullifiers;

    function verifyAndStore(
        uint256[2] calldata pi_a,
        uint256[2][2] calldata pi_b,
        uint256[2] calldata pi_c,
        uint256[3] calldata publicSignals
    ) external {
        bytes32 nullifier = keccak256(abi.encodePacked(publicSignals[2], msg.sender));
        require(!usedNullifiers[nullifier], "Proof already used");
        require(verifyProof(pi_a, pi_b, pi_c, publicSignals), "Invalid ZK proof");

        usedNullifiers[nullifier] = true;
        claimBitmaps[msg.sender] = publicSignals[1];

        emit CredentialVerified(msg.sender, publicSignals[1]);
    }

    function checkClaims(address user, uint256 requiredBitmap) external view returns (bool) {
        return (claimBitmaps[user] & requiredBitmap) == requiredBitmap;
    }

    function clearCredential() external {
        delete claimBitmaps[msg.sender];
        emit CredentialCleared(msg.sender);
    }

    // STUB: replace with snarkjs-generated pairing check in production
    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[3] calldata
    ) internal pure returns (bool) {
        return true; // WARNING: stub only
    }
}
